<div class="grid grid-cols-1 md:grid-cols-2 gap-5">
    <div><label class="block text-sm font-semibold mb-2">Nama pelanggan</label><input name="customer_name" value="<?php echo e(old('customer_name', $order->customer_name ?? '')); ?>" class="w-full rounded-xl border-gray-300"></div>
    <div><label class="block text-sm font-semibold mb-2">Nomor WhatsApp</label><input name="customer_phone" value="<?php echo e(old('customer_phone', $order->customer_phone ?? '')); ?>" class="w-full rounded-xl border-gray-300"></div>
    <div class="md:col-span-2"><label class="block text-sm font-semibold mb-2">Alamat</label><textarea name="customer_address" rows="3" class="w-full rounded-xl border-gray-300"><?php echo e(old('customer_address', $order->customer_address ?? '')); ?></textarea></div>
    <div class="md:col-span-2"><label class="block text-sm font-semibold mb-2">Item pesanan <span class="text-red-500">*</span></label><textarea name="items_text" rows="5" required class="w-full rounded-xl border-gray-300" placeholder="Nama produk | jumlah | harga satuan"><?php echo e(old('items_text', isset($order) ? collect($order->items)->map(fn ($item) => $item['name'].' | '.$item['qty'].' | '.$item['price'])->join("\n") : '')); ?></textarea><p class="text-xs text-gray-400 mt-1">Satu item per baris dengan format: Nama produk | jumlah | harga satuan.</p></div>
    <div><label class="block text-sm font-semibold mb-2">Total (Rp) <span class="text-red-500">*</span></label><input type="number" min="0" name="total_price" required value="<?php echo e(old('total_price', $order->total_price ?? '')); ?>" class="w-full rounded-xl border-gray-300"></div>
    <div><label class="block text-sm font-semibold mb-2">Status <span class="text-red-500">*</span></label><select name="status" class="w-full rounded-xl border-gray-300"><?php $__currentLoopData = $statuses; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $status): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($status); ?>" <?php if(old('status', $order->status ?? 'Menunggu konfirmasi') === $status): echo 'selected'; endif; ?>><?php echo e($status); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
    <div class="md:col-span-2"><label class="block text-sm font-semibold mb-2">Catatan</label><textarea name="notes" rows="3" class="w-full rounded-xl border-gray-300"><?php echo e(old('notes', $order->notes ?? '')); ?></textarea></div>
</div>
<?php if($errors->any()): ?><div class="mt-4 text-sm text-red-600"><?php echo e($errors->first()); ?></div><?php endif; ?>
<?php /**PATH C:\Users\USER\Perfu.me\resources\views/orders/_form.blade.php ENDPATH**/ ?>