<div class="grid grid-cols-1 md:grid-cols-2 gap-5">
    <div><label class="block text-sm font-semibold mb-2">Nama pelanggan</label><input name="customer_name" value="{{ old('customer_name', $order->customer_name ?? '') }}" class="w-full rounded-xl border-gray-300"></div>
    <div><label class="block text-sm font-semibold mb-2">Nomor WhatsApp</label><input name="customer_phone" value="{{ old('customer_phone', $order->customer_phone ?? '') }}" class="w-full rounded-xl border-gray-300"></div>
    <div class="md:col-span-2"><label class="block text-sm font-semibold mb-2">Alamat</label><textarea name="customer_address" rows="3" class="w-full rounded-xl border-gray-300">{{ old('customer_address', $order->customer_address ?? '') }}</textarea></div>
    <div class="md:col-span-2"><label class="block text-sm font-semibold mb-2">Item pesanan <span class="text-red-500">*</span></label><textarea name="items_text" rows="5" required class="w-full rounded-xl border-gray-300" placeholder="Satu nama item per baris">{{ old('items_text', isset($order) ? collect($order->items)->pluck('name')->join("\n") : '') }}</textarea><p class="text-xs text-gray-400 mt-1">Untuk pesanan otomatis, detail qty dan harga sudah disimpan sebagai snapshot.</p></div>
    <div><label class="block text-sm font-semibold mb-2">Total (Rp) <span class="text-red-500">*</span></label><input type="number" min="0" name="total_price" required value="{{ old('total_price', $order->total_price ?? '') }}" class="w-full rounded-xl border-gray-300"></div>
    <div><label class="block text-sm font-semibold mb-2">Status <span class="text-red-500">*</span></label><select name="status" class="w-full rounded-xl border-gray-300">@foreach($statuses as $status)<option value="{{ $status }}" @selected(old('status', $order->status ?? 'Menunggu konfirmasi') === $status)>{{ $status }}</option>@endforeach</select></div>
    <div class="md:col-span-2"><label class="block text-sm font-semibold mb-2">Catatan</label><textarea name="notes" rows="3" class="w-full rounded-xl border-gray-300">{{ old('notes', $order->notes ?? '') }}</textarea></div>
</div>
@if($errors->any())<div class="mt-4 text-sm text-red-600">{{ $errors->first() }}</div>@endif
